puppetlabs/trapperkeeper-metrics

- documentation/configuration.md
- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_core_test.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
Previously we have allowed the user to disable the creation of a
MetricsRegistry with the `metrics.enabled` option, though this means
the developer had to guard against a nil registry in all codepaths.
Metrics collection is very light and so here we make the change to
always create a MetricsRegisty, and log a warning message if
`metrics.enabled` is provided.
> TK-252 Always build a metrics registry, deprecate metrics.enabled

- documentation/index.md
- project.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_utils.clj
- src/puppetlabs/trapperkeeper/services/metrics/ringutils.clj
- src/puppetlabs/trapperkeeper/services/protocols/metrics.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_core_test.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This PR adds the ability to use multiple registries with tk-metrics by adding a protocol function that "upserts" registries on calls to `(get-metrics-registry <name of registry> <opts>)`
> (PDB-1531) Add mbeans handler and ability to configure multiple registries

- documentation/index.md
- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- src/puppetlabs/trapperkeeper/services/protocols/metrics.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
Prior to this commit when configuring multiple registries, a user could
create 2 different registries using the same domain, which cause one
jmx-reporter to shaadow the other, this commit uses the domain as the
lookup for the metrics-service atom which enforces `domain` uniqueness.
> (maint) Use `domain` string for registry lookup

- documentation/index.md
- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This commit adds a POST endpoint for `/v1/mbeans` which accepts a JSON
array of metrisc and returns an array of the values of these metrics.
> (maint) Add POST endpoint for querying multiple metrics at once

- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This commit fixes the broken get-metrics-registry call after the domain
passing change where we now use the domain for metrics-registry lookup.
> (maint) Fix broken get-metrics-registry call after domain change

- project.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
This commit is for the i18n of puppet server repositories. 
- externalize strings
- add i18n libraries
- set up middleware to allow for i18n to work on strings in HTTP requests
- add Makefile with fixed typo
Note that the Makefile will be overwritten each time `lein i18n init` is called. The Makefile committed in this PR is for the sake of letting users know that this typo needs to be fixed manually until [this PR](https://github.com/puppetlabs/clj-i18n/pull/22) gets merged into the clj-i18n library.
> (PE-16072) (PE-15848) Add i18n libraries to trapperkeeper-metrics 

- project.clj
TK metrics happens by luck to pull in the correct servlet-api dependency
through ring-servlet. This commit just makes it explicit so that downstream
consumers aren't at risk of missing it/having to specify the dependency
themselves
> (MAINT) Explicity add servlet api dependency

- src/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- src/puppetlabs/trapperkeeper/services/protocols/metrics.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
Add an `initialize-registry-settings` function to the MetricsService protocol.
In trapperkeeper-metrics the implementation of this function does not do
anything.
> (PE-14959) Add initialize-registry-settings to protocol

- src/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
Previously, the `/metrics` endpoint was only enabled if the `jmx` reporter was
enabled in the `reporters` section of the config. However, even if jmx isn't enabled for our registries, other mbeans will be
available - e.g. memory usage mbeans and jetty mbeans.
This commit makes it so that even if jmx is not enabled, if the
`metrics-webservice` has been added to the config then the `/metrics` endpoint
will be present.
> (PE-17031) Don't require jmx to be enabled for the metrics endpoint

- src/puppetlabs/metrics.clj
This patch corrects a typoed `^:alwyas-validate` to `^:always-validate`.
> (maint) Fix typo in schema defn metadata

- .travis.yml
- project.clj
This patch updates the dependencies in project.clj and adds
puppetlabs/clj-parent as the source of most dependency version using
clj-parent.
> Update dependencies and set parent project

- dev-resources/puppetlabs/trapperkeeper/services/metrics/metrics_service_test/jolokia-access-permissive.xml
- documentation/configuration.md
- project.clj
- resources/jolokia-access.xml
- src/puppetlabs/trapperkeeper/services/metrics/jolokia.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- src/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This patch adds the jolokia-core library to the dependency list and
mounts its servlet at 'metrics/v2' when the `metrics-webservice` is in
use. Jolokia is a small library that wraps a REST API around JMX and
provides great features such as globbing, attribute extraction and much
more.
Example query using globbing and parameter extraction:
```
curl -k 'https://localhost:8140/metrics/v2/read/java.lang:name=*,type=GarbageCollector/CollectionCount,CollectionTime'
```
**CAVEATS**
- The Jolokia API also exposes JMX control functionality, so "write"
and "exec" operations are currently restricted by a static
authorization configuration in `resources/jolokia-access.xml`.
- The servlet is currently mounted directly using the WebserverService
add-servlet-handler method, instead of going through the …
> (TK-404) Add jolokia Servlet as metrics/v2

- project.clj
This commit removes the following explicit dependencies from the
project.clj file since these are not referenced anywhere in the
tk-metrics code:
* ring/ring-core
* javax.servlet/javax.servlet-api
* org.slf4j/slf4j-api
An exclusion is explicitly used for the javax.servlet-api dependency
from ring/ring-defaults since the ring-defaults version being inherited
is known to bring in a version of javax.servlet-api which we don't want.
The servlet-api dependency will be picked up from clj-parent /
ring-middleware via ring 1.4.0, which pulls in javax.servlet-api 3.1.0.
> (MAINT) Remove explicit ring-core, servlet-api, and slf4j-api deps

- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
Cheshire's parse-stream will return a lazy-seq if the top level JSON
structure is an array. Currently the code calls parse-stream inside a
with-open block and for larger arrays this will cause the lazy-seq to
be realized after the stream has been closed causing an
exception. This commit just wraps that in a doall to ensure the seq is
realized before closing the stream.
> (TK-427) Request stream is closed before parsing finishes

- src/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_core_test.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
The PE implementation of this protocol enforces that only keywords be
used for the metric domains, whereas this implementation takes strings.
In the future both implementations will only take keywords, since the
domain is used as a lookup key so a keyword is a better fit. In light of
this, change this implementation to take keywords or strings so it's
easy for consumers to use this implementation or the PE one, and in the
future we can make the breaking change of only accepting keyword
domains.
> (TK-394) Accept keyword or string metric domains.

- src/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- src/puppetlabs/trapperkeeper/services/protocols/metrics.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
Add a `get-server-id` function to the metric service, which returns the
`server-id` from the config.
> (TK-433) Add `get-server-id` service function

- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
Previously, the tk-metrics service didn't have the
`initialize-registry-settings` service function implemented, and the service
would throw an exception if you tried to call it. However, it was recently
updated so that the function is implemented, but the test for this behavior
was still present. The test was incorrectly passing because it was now
throwing a schema error. This commit removes the bad test.
> (maint) Remove bad test

- documentation/configuration.md
- src/clj/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_core_test.clj
Update tk-metrics to only take domains as keywords
The metrics service originally only accepted domains as strings,
and then eventually it was decided keywords would be better, and
a PR was created to make the registry functions take in either
strings or keywords to maintain backward compatibility until we
decided to make the breaking change.
That moment has arrived, and so this commit removes the last
references to domains as strings.
This PR is part of a larger set of work to move metrics capabilities into OSS puppetserver from PE, see https://tickets.puppetlabs.com/browse/SERVER-1259
> (TK-394) Pass in domain as keyword only

- documentation/api.md
- documentation/metrics_reporting_and_filtering.md
- examples/ring_app/README.md
- examples/ring_app/src/examples/ring_app/ring_app.clj
- src/clj/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
- src/clj/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
- src/clj/puppetlabs/trapperkeeper/services/protocols/metrics.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_core_test.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This commits changes the behavior of initialize-registry-settings to allow it
to be called more than once for one domain, allowing multiple services to add
in the metrics they would like to whitelist for their domain.
As before, the first call will create the settings. Additional calls with the
same domain will merge and append the new settings to the old settings.
Since the only registry setting is currently :default-metrics-allowed, this
allows multiple TK services to call this service function, adding in their own
list of allowed metrics. Before, only one call could be made per domain, which
meant that you would have to designate a service to be the one that knows about
the list of metrics and initialize them.
> (TK-436) Add support for appending registry settings

- CHANGELOG.md
This is a major backwards incompatible feature release
* [TK-361](https://tickets.puppetlabs.com/browse/TK-361) - Move pe-trapperkeeper-metrics metrics code into OSS trapperkeeper-metrics
* [TK-393](https://tickets.puppetlabs.com/browse/TK-393) - Make jmx enabled per-registry. Deprecate enabling jmx globally
* [TK-394](https://tickets.puppetlabs.com/browse/TK-394) - Only accept metrics domain as keyword instead of string
* [TK-436](https://tickets.puppetlabs.com/browse/TK-436) - Add support for appending registry settings from multiple services
> (MAINT) Update changlog for 1.0.0 release

- project.clj
This patch updates the clj-parent dependency to 1.3.0 and drops a now-obsolete
exclusion of `javax.servlet/servlet-api` from the `ring/ring-defaults`
dependency.
> (maint) Update clj-parent to 1.3.1

- project.clj
The commit updates the dependency on jolokia-core to 1.5.0 which is the current
stable version. 1.5.0 includes two security fixes that do not affect
trapperkeeper-metrics usage:
- An XSS vulnerability that only affects browsers and is already mitigated by
the jolokia javascript library used by most dasboards that consume data
from Jolokia. Trapperkeeper does not bundle any of these dashboards.
- A vulnerability that allowed unrestricted proxying of JMX requests via
JSR160. Requires a dependency on the jolokia-jsr160 artifact, which
trapperkeeper-metrics does not have, along with dispatcherClasses to
be configured to include `org.jolokia.jsr160.Jsr160RequestDispatcher`.
> (maint) Update Jolokia dependency to 1.5.0

- project.clj
The commit updates the dependency on jolokia-core to 1.6.0 which is
the current stable version. 1.6.0 improved the security posture of
the WAR agent. Trapperkeeper metrics uses the JAR agent, so this
update is mostly a noop, but it is good to stay current.
> (maint) Update Jolokia dependency to 1.6.0

- .travis.yml
- project.clj
This changeset has several small maintenance commits:
- Update the Travis CI configuration. Drop OracleJDK 8 as the test platform in favor of OpenJDK 8.
- Update clj-parent dependency to 1.7.26
- Update jolokia dependency to 1.6.1
> Various and sundry updates

- CHANGELOG.md
- src/clj/puppetlabs/trapperkeeper/services/metrics/metrics_service.clj
This commit adds a deprecation warning that prints on service start when
the v1 metrics endpoint is enabled. This endpoint is currently disabled
by default and will be removed entirely in a later release.
> (TK-486) Add deprecation warning to v1 metrics endpoint

- CHANGELOG.md
- project.clj
- resources/jolokia-access.xml
Now that the metrics endpoints can be accessed via an authenticated
connection, we can expose them outside of localhost.
> (PE-28647) Remove localhost-only access restriction

- .travis.yml
- ext/travisci/test.sh
- project.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This picks up an update to ring-parent which mitigates a known
vulnerability in commons-fileupload.
> (PE-31012) Update to latest clj-parent

- project.clj
- src/clj/puppetlabs/trapperkeeper/services/metrics/metrics_core.clj
Prior to this commit, tk-metrics was using ring-defaults/api-defaults wrappers. This commit replaces that with direct calls to the ring.middleware wrappers needed for the API endpoints.
Also updates clj-parent to v6.0.1
> (PE-36390) replace use of ring-defaults

- CHANGELOG.md
- project.clj
Ran 33 tests containing 280 assertions.
0 failures, 0 errors.
> (PE-36484) Bump tk-jetty to address Jetty ring handler broken function

- CHANGELOG.md
- project.clj
In order to move to centralized management of trapperkeeper-webserver-jetty-10, this
moves to clj-parent 7.3.6, and removes the version pin from tk-ws-jetty-10
Other outdated dependencies were also updated.
Additionally, profile declarations that mixed keys of other profiles and
maps were refactored to just include keys as the previous format is now
deprecated and not recommended.
It also prepares for a release.
> (PE-37632) update clj-parent to manage tk-ws-jetty10

- CHANGELOG.md
- project.clj
This adds the license key to the project.clj to allow the project to be published to clojars.
It also updates the changelog
> (maint) add license key, update changelog

- .github/workflows/lein-test.yaml
- project.clj
- test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
This removes the dev-resources from the jar, which will stop all the projects that include tk-metrics from complaining about multiple logback files in the classpath when their tests are run.
It also cleans up the test output when running tk-metric's tests.
> (maint) Clean up some annoying issues
